### ISSUE TITLE
Live tracker does not work

### ISSUE THREAD

**Issue by vanto** [matthewghgriffiths/rowing#1]
Thanks for this interesting project.

Unfortunately the live tracker does not work (anymore?). I assume that the json schema of the live tracking data has been changed and breaks the parser.

From a brief check it looks like intermediates and live data have been moved from top level to the lanes element, but for me it is difficult to understand what needs to be changed without having an example instance of a working json file.

**Comment by matthewghgriffiths** [comment]
Yeah, WorldRowing changed the api, I've mostly updated the API, but I haven't got round to pushing the changes yet.

**Comment by matthewghgriffiths** [comment]
OK, I think it should work now, sorry it's a little late for Europeans

**Comment by vanto** [comment]
Awesome, thanks. Seems to work.

Don't remind me of the Europeans :) GER probably has some homework to do...

**Comment by matthewghgriffiths** [comment]
My commiserations, as a GBR supporter I know the pain of rebuilding. Let me know if there are any features or visualisations you'd appreciate.
